API:
- api/**/*

CI/CD:
- .github/**/*
- .circleci/**/*
- .codebuild/**/*

CLI:
- cli/**/*

Contents Data:
- contents/projects/**/*

Doc:
- doc/**/*

Docker:
- docker/**/*
- api/dockerfiles/**/*

Frontend:
- front/**/*

proto:
- api/proto/**/*
- contents/proto/**/*

E2E:
- e2e/**/*

Landing Page:
- landing_page/**/*

Tools:
- tools/**/*
